site_name: CI testing
repo_url: https://github.com/DolphinGui/ci-test

nav:
  - Home: index.md

plugins:
  - search
  
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

